### ISSUE TITLE
Runner deadlocks if configuration fails

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/gha-self-hosted#15]
This happened on our VMs:
```
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: --------------------------------------------------------------------------------
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: |        ____ _ _   _   _       _          _        _   _                      |
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: |                                                                              |
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: |                       Self-hosted runner registration                        |
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: |                                                                              |
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: --------------------------------------------------------------------------------
Oct 06 18:18:33 ubuntu start-gha-runner[1267]: # Authentication
Oct 06 18:18:34 ubuntu start-gha-runner[1267]: Http response code: InternalServerError from 'POST https://api.github.com/actions/runner-registration'
Oct 06 18:18:34 ubuntu start-gha-runner[1267]: {"message":"Server Error","documentation_url":"https://docs.github.com/rest"}
Oct 06 18:18:34 ubuntu start-gha-runner[1267]: Response status code does not indicate success: 500 (Internal Server Error).
Oct 06 18:18:34 ubuntu start-gha-runner[878]: warning: failed to eject the CD-ROM
Oct 06 18:18:35 ubuntu start-gha-runner[878]: Traceback (most recent call last):
Oct 06 18:18:35 ubuntu start-gha-runner[878]:   File "/usr/local/bin/start-gha-runner", line 27, in <module>
Oct 06 18:18:35 ubuntu start-gha-runner[878]:     subprocess.run([
Oct 06 18:18:35 ubuntu start-gha-runner[878]:   File "/usr/lib/python3.8/subprocess.py", line 512, in run
Oct 06 18:18:35 ubuntu start-gha-runner[878]:     raise CalledProcessError(retcode, process.args,
Oct 06 18:18:35 ubuntu start-gha-runner[878]: subprocess.CalledProcessError: Command '['./config.sh', '--unattended', '--replace', '--url', 'https://github.com/rust-lang-ci/rust', '--token', 'AP2YLXGZTJMOETSZKS5K5227PTBNG', '--name', 'arm-1-1']' returned non-zero exit status 1.
```

We should either implement retry or shutdown the VM when that happens.

**Comment by pietroalbini** [comment]
I'm thinking a possibly better solution is to just add monitoring on whether the runner connected to GitHub or not. While just retrying would solve the problem in case of GitHub outages (like what I think happened here), there are a lot of situations where that would not really be useful (revoked token, wrong GitHub Actions Runner version...) and where manual intervention is required.

**Comment by pietroalbini** [comment]
Implementing monitoring is tracked @ https://github.com/rust-lang/monitorbot/issues/11
